spring:
  user:
    datasource:
      jdbc-url: jdbc:h2:mem:userdb
      username: useradmin
      password: useradmin
      liquibase:
        change-log: classpath:db/changelog/db.changelog-user-master.xml
  movie:
    datasource:
      jdbc-url: jdbc:h2:mem:moviedb
      username: movieadmin
      password: movieadmin
      liquibase:
        change-log: classpath:db/changelog/db.changelog-movie-master.xml
  h2:
    console:
      enabled: true
  jpa:
    properties:
      hibernate:
        hbm2ddl:
          auto: validate
